### PR TITLE
lz4k: Remove lz4k module

### PR DESCRIPTION
**Pull request by AlexLartsev19**

### CODE REVIEW

**Comment by micheleberrettis1** [comment]
just execute "make menuconfig" from kernel source folder and untick "enable lz4k module" in "device drivers>>block devices"

**Comment by Moyster** [comment]
@micheleberrettis1 : Well, LZ4K (mediatek's custom lz4) is not built by default in the kernel, this commit wants to remove "mediatek custom code". I'm not sure which wins LZ4 vs LZ4K (since both should beat LZO & LZ4HC) and that's why I never merged this.
I consider LZ4 to be +/- uptodate, which is why I use it, but it would be good for curiosity to find out which is better/faster.

**Comment by micheleberrettis1** [comment]
Oh i see... When i'll achieve building the kernel (stuck on makefile error) i'll try both and let you know!

**Comment by Moyster** [comment]
manually merged it instead of rebasing/fixing the conflicts, thanks.  
Anyway, to anyone who wonders, since the zram backported drivers, zcomp supports the crypto api, which means lz4k could've been used with it but it compiles fines, but the zram device ends up being 0mb, so... farewell lz4k.

**Pull request closed without merging**
