### PR TITLE
Port sdcardfs

### PR DESCRIPTION
**Pull request by AlexLartsev19**
I don't test building kernel after this commits. If you have any problems check my [mm-6.0-test branch ](https://github.com/AlexLartsev19/android_kernel_m2note/tree/mm-6.0-test)

### CODE REVIEW

**Comment by Moyster** [comment]
My sdcard died a few months ago, it's best you test this stuff and report if it's working.
Doesn't using sdcardfs need device tree / init files modifications too ?

**Comment by AlexLartsev19** [comment]
Ok, i compile kernel, test it and write about results.
No, only kernel. ;)

**Comment by AlexLartsev19** [comment]
Kernel not bulding.

 `WARNING: drivers/built-in.o(.text+0x30354c): Section mismatch in reference from the function spm_set_pcm_init_flag() to the function .init.text:of_scan_flat_dt()
The function spm_set_pcm_init_flag() references
the function __init of_scan_flat_dt().
This is often because spm_set_pcm_init_flag lacks a __init 
annotation or the annotation of of_scan_flat_dt is wrong.

WARNING: drivers/built-in.o(.text+0x308660): Section mismatch in reference from the function mt_usb_init() to the variable .init.data:$d
The function mt_usb_init() references
the variable __initdata $d.
This is often because mt_usb_init lacks a __initdata 
annotation or the annotation of $d is wrong.

WARNING: drivers/built-in.o(.text+0x308668): Section mismatch in reference from the function mt_usb_init() to the variable .init.data:$d
The function mt_usb_init() references
the variable __initdata $d.
This is often because mt_usb_init lacks a __initdata 
annotation or the annotation of $d is wrong.

WARNING: drivers/built-in.o(.data+0x69e08): Section mismatch in reference from the variable mt_spi_driver to the variable .init.text:$x
The variable mt_spi_driver references
the variable __init $x
If the reference is valid then annotate the
variable with __init* or __refdata (see linux/init.h) or name the variable:
*_template, *_timer, *_sht, *_ops, *_probe, *_probe_one, *_console

WARNING: drivers/built-in.o(.data+0x69f18): Section mismatch in reference from the variable spi_test_driver to the variable .init.text:$x
The variable spi_test_driver references
the variable __init $x
If the reference is valid then annotate the
variable with __init* or __refdata (see linux/init.h) or name the variable:
*_template, *_timer, *_sht, *_ops, *_probe, *_probe_one, *_console

Makefile:130: ошибка выполнения рецепта для цели «sub-make»
make: *** [sub-make] Ошибка 2
Kernel building succesful!
Creating ZIP...
cp: не удалось выполнить stat для '/home/alexlartsev19/blood_m2note/out/zImage': Нет такого файла или каталога
Cleaning after building...
alexlartsev19@mint18 ~/blood_m2note $ 
`
I am looking for a solution

**Comment by Moyster** [comment]
well, I'll clean this for now and close it.
I'm gonna start accepting pull requests only on a separate branch than "master / default".

**Pull request closed without merging**
