### PR TITLE
Make the hotplug run less frequently

### PR DESCRIPTION
**Pull request by DidntRead**

### CODE REVIEW

**Comment by Moyster** [comment]
Hi dude, thanks for the PR, any arguments in favor of moving back to 100 again ? I pushed this : https://github.com/Moyster/android_kernel_m2note/commit/dc15803a5e00bf1fb1d74da69a7fb09f37c35101 from the public motorola mt6735 kernel on lineageos github, not sure if moving back to 100 makes much of a difference but I pushed it because if the hotplug decisions are taken faster, this means the device will spend less time enabling/disabling cores, which is better for sudden load, like starting a huge apps.  

Not sure what to do there

**Comment by DidntRead** [comment]
I think 40 is the default while Motorola`s commit makes it 100 which should make the kernel spend less time powering up and down cores.
https://github.com/MotorolaMobilityLLC/kernel-mtk/commit/b7937f92be81fef1f50815ead13a227785b3f0f5

**Comment by Moyster** [comment]
Nice catch, I stopped there: https://github.com/MotorolaMobilityLLC/kernel-mtk/commit/8a6f86dd44e4fcd6e98723be45539693772eb317  
Thanks again :)

**Comment by DidntRead** [comment]
The fast merge wow

**Comment by Moyster** [comment]
Yh, I still have vacations and I barely slept since yesterday, been rebasing my kernel (branch ng-rebased) with clean ext4 / f2fs drivers to fix encryption... hopefully I can get the backported ext4 drivers from 3.18 working with encryption again, then the lazytime flags for amazing I/O perf, then maybe I'll take care of F2FS.  

If by any chance you have a clue at what I'm missing / broken in ng-7.1.2 and o-8.0.0, my kernel doesn't seem to be able to encrypt partitions, both vdc enablecrypt wipe and inplace (I get a "can't allocate crypto tfm" error, and a corrupted fs), but with my rebased kernel, I could encrypt /userdata, then reboot to TWRP with my ng-7.1.2 kernel inside, and it decrypted the partition properly, which makes me believe :  
ng-rebased use a working cipher to encrypt, lets call it A, i didn't check which.
ng-7.1.2 try to use a "better/more recent" cipher to encrypt, let's call it cipher B, but "can't allocate crypto tfm" happens.
if ng-rebased encrypt with cipher A, ng-7.1.2 supports cipher A and B, but decrypting works with cipher A only.  

Since I backported ext4 from 3.18 to 3.10, MAD merged the same ish patchset to their S3 device (https://github.com/MediatekAndroidDevelopers/android_kernel_jiayu_s3_h560), : ext4 3.18 + f2fs from 4.x + lazytime flags , it only lacks a few backports like the mbache2 conversion)
They have EXT4_FS_ENCRYPTION enabled, which makes me believe they are using the newer (3.18 backported) /fs/crypto code, where the "error can't allocate crypto tfm" happens.  

Any clue welcomed :>

**Pull request merged**
